url: https://jenhardin.github.io
baseurl: 

# Site settings
title: Jen Hardin
email: jennifer@jenniferhardin.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: 
  pic: 1
  position: 
  social:
    - title: github
      url: https://github.com/jenhardin
    - title: linkedin
      url: https://www.linkedin.com/in/jennifer-hardin-pdx/
    - title: instagram
      url: https://www.instagram.com/jennhardin/


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url:https://www.facebook.com/jenniferhardinphotography
  - title: stack-overflow
    url: https://stackoverflow.com/users/11313526/jen-hardin
  - title: linkedin 
    url: https://www.linkedin.com/in/jennifer-hardin-pdx/
  - title: github
    url: http://github.com/jenhardin

# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: Portland, OR 97266

# Build settings
markdown: kramdown
permalink: pretty
